"""Build the offline review index after capturing previews with verify.mjs."""

import base64
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIRECTIONS = [
    ("A", "a-flow-map", "Follow the flow", "Attach each exception to the step it changes.", "Tracing causality: where the process goes and where it stops.", "The complete map takes more vertical space.", "Which visual connection made a branch easier to understand?"),
    ("B", "b-storyboard", "Follow your words", "Use a concrete voice session and show its transformations together.", "Understanding what happens to a transcript or a selected phrase.", "Examples need explicit limits so one scenario does not appear universal.", "Did the example explain the request better than the component names?"),
    ("C", "c-lanes", "Follow the owners", "Place each action in its component’s lane and separate data by lifetime.", "Understanding parallel work, responsibility and what the next request remembers.", "Lanes are denser and need more horizontal room.", "Can you tell who owns each piece of data and when it disappears?"),
    ("D", "d-overview", "Start with the essentials", "Show the whole path and compare the main outcomes in a compact overview.", "Getting oriented quickly before reading source detail.", "Compression leaves less room for implementation nuance in the main view.", "What can be removed before the explanation becomes misleading?"),
]

sections = []
for ident, folder, title, thesis, best, tradeoff, question in DIRECTIONS:
    image = base64.b64encode((ROOT / "proof" / f"{folder}-diagram.png").read_bytes()).decode("ascii")
    sections.append(f'''<article id="{ident}">
<div class="heading"><span class="letter">{ident}</span><div><h2>{html.escape(title)}</h2><p>{html.escape(thesis)}</p></div></div>
<a class="preview" href="{folder}/index.html" aria-label="Open alternative {ident}: {html.escape(title)}"><img src="data:image/png;base64,{image}" alt="Rendered desktop preview of alternative {ident}. Open the full page to read the diagram."></a>
<div class="facts"><p><b>Useful for</b>{html.escape(best)}</p><p><b>Tradeoff</b>{html.escape(tradeoff)}</p></div>
<p class="question">Review question: {html.escape(question)}</p>
<div class="links"><a class="primary" href="{folder}/index.html">Open alternative {ident} →</a><a href="{folder}/rationale.md">Design reasoning &amp; skill proposal</a></div>
</article>''')

page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Handy architecture · Four ways to explain it</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#FAFBFC;color:#1A2230;font:16px/1.55 "Segoe UI",system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:42px 46px 70px}h1{font-size:clamp(30px,4vw,48px);letter-spacing:-.03em;line-height:1.12;margin:18px 0}h2{font-size:23px;line-height:1.2;margin:0 0 7px;letter-spacing:-.02em}p{margin:0 0 13px}a{color:#1E5A8A;text-underline-offset:3px}a:focus-visible{outline:3px solid #1E5A8A;outline-offset:5px}.intro{font-size:19px;color:#475569;max-width:76ch}.top{display:flex;justify-content:space-between;flex-wrap:wrap;gap:15px;font-size:13px}.top strong{color:#1E5A8A}.jump{display:flex;gap:9px;flex-wrap:wrap;padding:15px 0 24px}.jump a{border:1px solid #CBD5E1;border-radius:7px;text-decoration:none;padding:8px 15px;background:#fff}.review{background:#E8F0F8;border:1px solid #BFD4E8;border-radius:12px;padding:22px;margin:12px 0 30px}.review p{max-width:82ch}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:28px}article{background:white;border:1px solid #DDE3EA;border-radius:14px;overflow:hidden;scroll-margin-top:16px}.heading{display:flex;gap:16px;padding:24px 24px 18px}.heading p{font-size:14px;color:#475569;margin:0}.letter{font-size:23px;font-weight:700;display:grid;place-items:center;align-self:start;background:#E8F0F8;border-radius:8px;min-width:44px;height:44px;color:#1E5A8A}.preview{display:block;border-block:1px solid #DDE3EA;line-height:0}.preview img{width:100%;height:auto;display:block}.facts{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:20px 24px 0;font-size:14px}.facts b{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#475569;margin-bottom:6px}.question{padding:0 24px;font-size:14px;color:#475569}.links{display:flex;gap:15px;align-items:center;flex-wrap:wrap;padding:8px 24px 24px;font-size:13px}.primary{background:#1E5A8A;color:white;border-radius:7px;text-decoration:none;padding:10px 14px;font-weight:600}.primary:hover{background:#16446A}section{margin-top:40px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;vertical-align:top;padding:13px;border-bottom:1px solid #DDE3EA}th{background:#F1F4F7}.table{overflow:auto}li{margin:9px 0}code{font-family:Consolas,monospace;font-size:13px;background:#F1F4F7;padding:2px 5px;border-radius:3px}footer{border-top:1px solid #DDE3EA;padding-top:20px;margin-top:35px;font-size:12px;color:#475569}::selection{background:#BFD4E8}nav a:hover{background:#E8F0F8}@media(max-width:950px){.comparison{grid-template-columns:1fr}main{padding:25px}.preview img{max-height:620px;object-fit:cover;object-position:top}}@media(max-width:500px){main{padding:18px}.facts{grid-template-columns:1fr;gap:0}.heading{padding:19px}.question{padding:0 19px}.links{padding:8px 19px 20px}.intro{font-size:17px}.review{padding:18px}.top{font-size:12px}}
</style></head><body><main>
<div class="top"><strong>Handy · Architecture explanation alternatives</strong><a href="../context-profiles-architecture.html">Compare with the original walkthrough</a></div>
<h1>Four ways to make the flow visible.</h1>
<p class="intro">The same architecture, explained through four different structures. Every alternative exposes cancellation, focus changes, changed input, invalid replies and protected fields without a dropdown.</p>
<nav class="jump" aria-label="Alternative previews"><a href="#A">A · Flow map</a><a href="#B">B · Storyboard</a><a href="#C">C · Responsibility lanes</a><a href="#D">D · Concise overview</a><a href="#skill">Proposed skill changes</a></nav>
<div class="review"><p><b>Compare the same three moments:</b> audio and context run together; the request separates instructions from data; output can be blocked and automatic learning is still pending.</p><p style="margin:0">Open any full page below. Reply with <b>A, B, C or D</b>, a combination, or what you want a fresh round to explore. These are presentation choices; they do not resolve the separate learning decision G1.</p></div>
<div class="comparison">@@SECTIONS@@</div>
<section id="skill"><h2>What this round proposes for show-me</h2><p>Each Astra agent wrote a rationale beside its page. These proposals remain local for review; the installed skill has not been changed.</p><div class="table"><table><thead><tr><th>Current problem</th><th>Proposed instruction</th><th>Where to evaluate it</th></tr></thead><tbody>
<tr><td>The reader must discover cases in a dropdown.</td><td>Expose the primary flow and material branches on first reading. Use controls to emphasize or manipulate already visible relationships.</td><td>A’s attached branches; B’s exception strips; C’s matrix; D’s outcome comparison.</td></tr>
<tr><td>Prose lists components without making relationships visible.</td><td>Choose a representation by the question: causal map, concrete storyboard, ownership lanes, or compact overview.</td><td>Compare A–D using the review questions under each preview.</td></tr>
<tr><td>Several states require remembering what the previous screen showed.</td><td>Place the states being compared together. Show what changed, where the path stops, and what happens next.</td><td>All five failure cases stay visible.</td></tr>
<tr><td>Evidence can dominate the explanation.</td><td>Lead with the flow; keep short evidence references beside claims and put source excerpts after the main explanation.</td><td>Read the diagrams first, then inspect each page’s evidence.</td></tr>
<tr><td>A polished diagram can imply completed behavior.</td><td>Mark implemented, pending and unverified behavior in the diagram itself. Separate illustration from runtime proof.</td><td>The missing learning path and destination support limits.</td></tr>
</tbody></table></div><p><a href="SHOW-ME-PROPOSAL.md">Read the consolidated proposal</a> · <a href="BRIEF.md">Shared brief and review criteria</a></p></section>
<section><h2>Review status</h2><p>All four pages were built by separate GPT-6-Astra agents and reviewed against the current code. Desktop and narrow layouts, offline assets, section links, script errors and no-JavaScript visibility were checked in Microsoft Edge. Screenshots above are previews of the explanation pages, not screenshots of new Handy app functionality.</p><p><b>No direction is selected.</b> The original walkthrough is available for comparison. A new round can explore a plainer, denser or more visual treatment.</p></section>
<footer>Scope: documentation prototypes and proposed skill instructions. App behavior and the installed show-me skill are unchanged. Evidence of page checks: <code>design/alternatives/proof/</code>. Rebuild previews with <code>node design/alternatives/verify.mjs</code>, then rebuild this index with <code>uv run design/alternatives/build-index.py</code>.</footer>
</main></body></html>'''.replace("@@SECTIONS@@", "\n".join(sections))
(ROOT / "index.html").write_text(page, encoding="utf-8")
print(f"Built {ROOT / 'index.html'}")
