"""Build the third review round from inspected candidate screenshots."""

import base64
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIRECTIONS = [
    ("H", "h-connected-map", "Connected architecture map", "Start with the whole system, then follow its connections into the details.", "Can you follow the work and understand who handles each part?"),
    ("I", "i-illustrated-session", "One illustrated voice session", "Follow one concrete recording through configuration, context, request and output.", "Does following the example explain how the pieces work together?"),
    ("J", "j-reader-questions", "The reader’s questions", "Use the overview to orient yourself, then read direct answers to the central questions.", "Do the questions answer what you need without hiding the architecture?"),
]
cards = []
for ident, folder, title, intro, question in DIRECTIONS:
    preview = base64.b64encode((ROOT / "proof" / f"{folder}-desktop.png").read_bytes()).decode("ascii")
    cards.append(f'''<article id="{ident}"><header><span class="letter">{ident}</span><h2>{escape(title)}</h2><p>{escape(intro)}</p><a class="open" href="{folder}/index.html">Open {ident}</a></header><a class="preview" href="{folder}/index.html" aria-label="Open design {ident}"><img src="data:image/png;base64,{preview}" alt="Desktop preview of alternative {ident}. Open the full explanation to read it."></a><div class="review"><p>{escape(question)}</p><a href="{folder}/SKILL-PROPOSAL.md">Generic instruction proposal</a><a href="{folder}/rationale.md">Design reasoning</a></div></article>''')
page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Architecture explanations · Round 3</title><style>
*{box-sizing:border-box}body{margin:0;background:#fafbfc;color:#1a2230;font:16px/1.55 "Segoe UI",sans-serif}main{max-width:1500px;margin:auto;padding:28px 36px 50px}a{color:#1e5a8a;text-underline-offset:3px}a:focus-visible{outline:3px solid #d97706;outline-offset:4px}.nav{display:flex;gap:20px;flex-wrap:wrap;font-size:13px}h1{font-size:38px;letter-spacing:-.025em;line-height:1.15;margin:25px 0 12px}h2{font-size:22px;line-height:1.2;margin:5px 0 12px}p{margin:0 0 14px}.intro{max-width:80ch;color:#475569;font-size:18px}.kept{margin:22px 0 30px;padding:16px 0;border-block:1px solid #dde3ea;display:flex;gap:28px;font-size:14px}.kept p{flex:1;margin:0}.kept b{display:block;margin-bottom:4px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}article{border:1px solid #dde3ea;border-radius:12px;overflow:hidden;background:white}article header{padding:20px}.letter{font-size:14px;font-weight:700;color:#1e5a8a}article header p{color:#475569;font-size:14px;min-height:66px}.open{background:#1e5a8a;color:white;text-decoration:none;padding:9px 19px;border-radius:6px;display:inline-block;font-size:14px}.preview{display:block;border-block:1px solid #dde3ea}.preview img{display:block;width:100%;height:auto}.review{padding:18px 20px;font-size:14px}.review a{display:block;margin-top:8px;font-size:12px}.after{margin-top:30px;padding-top:20px;border-top:1px solid #dde3ea;max-width:85ch}.after h2{font-size:24px}.after p{font-size:15px}footer{font-size:12px;color:#475569;margin-top:28px}::selection{background:#bfd4e8}@media(max-width:1000px){.grid{grid-template-columns:1fr}.kept{display:block}.kept p+p{margin-top:12px}article header p{min-height:0}.preview img{max-height:700px;object-fit:contain}main{padding:22px}}@media(max-width:500px){main{padding:18px}h1{font-size:30px}.intro{font-size:16px}}
</style></head><body><main><nav class="nav" aria-label="Review history"><a href="../c-lanes/index.html">Revisit C</a><a href="../round-2/f-two-runs/index.html#G1">F’s question section</a><a href="../round-2/index.html">Previous round</a><a href="BRIEF.md">This round’s brief</a></nav><h1>Three new ways to explain the architecture</h1><p class="intro">E, F and G did not work as complete designs. This round preserves the pieces you liked and changes how the explanation is built around them.</p><div class="kept"><p><b>Keep</b>Overview flows, annotated captures of the real app, C’s visible responsibilities, and F’s open questions.</p><p><b>Improve</b>Labels you can understand, reasons beside the relevant behavior, and a complete path from startup to the next recording.</p><p><b>Compare</b>A connected map, one illustrated session, and an explanation organized around reader questions.</p></div><div class="grid">@@CARDS@@</div><section class="after"><h2>Choose the parts that communicate</h2><p>You can select H, I or J, combine useful pieces, or reject the round. No direction is selected. The same open product question appears in each page; choosing a presentation does not answer that product question.</p><p>Each page has a separate instruction proposal written for use across projects. The installed skill and application behavior are unchanged.</p></section><footer>Checked in Edge at desktop and narrow widths, with JavaScript disabled: local links, embedded images, overflow and absence of external asset requests. These checks do not prove reader comprehension or a live voice-to-output run. Existing native captures retain their original provenance. <a href="TASKS.md">Review and verification record</a>.</footer></main></body></html>'''.replace("@@CARDS@@", "\n".join(cards))
(ROOT / "index.html").write_text(page, encoding="utf-8")
print(ROOT / "index.html")
