"""Create the round-2 comparison from the inspected prototype screenshots."""

import base64
import json
import re
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROOF = ROOT.parents[1] / "proof" / "architecture"
capture = json.loads((PROOF / "capture.json").read_text(encoding="utf-8-sig"))
dictionary_image = base64.b64encode((PROOF / "dictionary-annotated.png").read_bytes()).decode("ascii")
overlay_image = base64.b64encode((PROOF / "overlay.png").read_bytes()).decode("ascii")
original = (ROOT.parents[1] / "context-profiles-architecture.template.html").read_text(encoding="utf-8")
overview = re.search(r'<svg viewBox="0 0 980 290".*?</svg>', original).group(0)
for old, new in {
    "Managers + stores": "Load saved settings",
    "Invoke recording": "Start recording",
    "New session + target": "Remember destination",
    "Capture → route → freeze": "Choose profile + input",
    "Context lane · widget updates": "Keep a copy; update widget",
    "Existing audio lane": "Turn speech into text",
    "Existing HTTP client": "Send instructions + data",
    "Prediction + effect": "Rewritten text + proposed action",
    "Session / field / focus": "Check original destination",
}.items():
    overview = overview.replace(old, new)
# Give the endpoint explanation room without changing the diagram's connections.
overview = overview.replace('x="883" y="142" font-size="11"', 'x="883" y="142" font-size="9"')
retained = f'''<section class="retained" id="retained"><h2>Keep the overview and the real app</h2><p>Shared direction for E, F and G: familiar action labels explain the flow; annotated captures connect it to what you see.</p><div class="overview">{overview}</div><p class="caption">Adapted from the original code-derived overview. The upper branch groups steps that inspect the focused app/input, choose a profile, and keep that recording’s context. It runs alongside audio recording; both results are needed before the request. It is a group of steps, not a function named “Context lane”. Startup also prepares the components that handle audio, models, transcription and history. <a href="../../context-profiles-architecture.html#evidence">Original source evidence</a>.</p><div class="capture-grid"><figure><img class="app-shot" src="data:image/png;base64,{dictionary_image}" alt="Real Handy profile settings annotated with the profile selector, profile tabs and canonical keyword mapping."><figcaption>Existing native capture: ① profile being edited, ② its three tabs, ③ canonical keyword and misheard forms. Synthetic profile data; no tenant. Captured {escape(capture['captured_at'])}; baseline 8f9cf53 plus the working-tree changes at capture time. Reused for this design review, not recaptured.</figcaption></figure><div><h3>Connect the screen to the flow</h3><p>The profile you edit supplies the rules and dictionary. When recording starts, the focused app determines which profile Handy uses.</p><img src="data:image/png;base64,{overlay_image}" width="256" height="50" alt="Real Handy overlay showing the terminal profile icon in the leftmost position."><p class="caption">Existing native overlay capture using a synthetic session event, not microphone audio. Its terminal icon replaces the left dot.</p><p>The diagram explains how the profile is chosen. The annotated screen shows where you configure it. Neither image proves that the entire voice-to-paste sequence completed.</p><h3>Words should identify their subject</h3><p>Use project terms the reader knows. Explain new terms where they appear. State whether a label names a real component, an action, or a visual group of steps.</p></div></div></section>'''
directions = [
    ("E", "e-purpose-lanes", "Explain each handoff", "Keep the ownership lanes and put the design reason beside the consequential exchanges.", "Does the flow explain why the pieces are separated?", "Rationale stays close to the mechanism.", "Extra labels can crowd a dense sequence."),
    ("F", "f-two-runs", "Compare two operations", "Align successive runs so unchanged inputs, changing inputs and possible reuse can be compared directly.", "Can you distinguish resending data from reusing computation?", "A comparison exposes the difference without relying on memory.", "Repeated structure takes room and needs a carefully bounded example."),
    ("G", "g-boundaries", "Explain the boundaries", "Keep a small system map, then connect it to visible closeups of the important boundaries.", "Can you connect each design reason to the boundary it explains?", "The overview remains compact while the closeups carry the rationale.", "The reader must follow references between overview and closeups."),
]
cards = []
for ident, folder, title, intro, question, strength, tradeoff in directions:
    png = base64.b64encode((ROOT / "proof" / f"{folder}-desktop.png").read_bytes()).decode("ascii")
    cards.append(f'''<article id="{ident}"><div class="card-head"><span class="id">{ident}</span><h2>{escape(title)}</h2><p>{escape(intro)}</p></div><a class="preview" href="{folder}/index.html" aria-label="Open alternative {ident}"><img src="data:image/png;base64,{png}" alt="Rendered preview of alternative {ident}; open the full page to inspect its diagrams."></a><div class="card-body"><p><b>Strength</b>{escape(strength)}</p><p><b>Tradeoff</b>{escape(tradeoff)}</p><p class="question">{escape(question)}</p><a class="primary" href="{folder}/index.html">Open {ident} →</a><div class="secondary"><a href="{folder}/SKILL-PROPOSAL.md">Generic skill instructions</a><a href="{folder}/rationale.md">Reasoning and transfer example</a></div></div></article>''')

page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Round 2 · Architecture, purpose and evidence</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#FAFBFC;color:#1A2230;font:15px/1.6 "Segoe UI",system-ui,sans-serif}main{max-width:1540px;padding:26px 38px 55px;margin:auto}a{color:#1E5A8A;text-underline-offset:3px}a:focus-visible{outline:3px solid #1E5A8A;outline-offset:4px}.top{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;font-size:13px}.top strong{color:#1E5A8A}h1{font-size:clamp(29px,3vw,42px);line-height:1.14;letter-spacing:-.03em;margin:25px 0 12px}h2{font-size:23px;line-height:1.2;margin:8px 0 12px}p{margin:0 0 12px}.intro{font-size:18px;color:#475569;max-width:83ch}.principle{display:flex;gap:24px;border-block:1px solid #DDE3EA;padding:17px 0;margin:23px 0 28px}.principle p{margin:0;flex:1;font-size:14px}.principle strong{display:block;color:#1E5A8A;margin-bottom:4px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}article{border:1px solid #DDE3EA;background:white;border-radius:12px;overflow:hidden}.card-head{padding:21px 22px 12px}.card-head p{font-size:14px;color:#475569;min-height:68px}.id{color:#1E5A8A;font-size:15px;font-weight:750}.preview{display:block;line-height:0;border-block:1px solid #DDE3EA}.preview img{display:block;width:100%;height:auto}.card-body{padding:20px 22px}.card-body p{font-size:13px}.card-body b{display:block;font-size:11px;letter-spacing:.05em;text-transform:uppercase;color:#475569;margin-bottom:3px}.question{border-top:1px solid #DDE3EA;padding-top:13px;margin-top:16px!important;font-weight:600}.primary{display:inline-block;padding:9px 17px;color:white;background:#1E5A8A;text-decoration:none;border-radius:6px;font-weight:600;font-size:13px;margin:4px 0 13px}.primary:hover{background:#16446A}.secondary{display:grid;gap:7px;font-size:12px}.after{display:grid;grid-template-columns:1fr 1fr;gap:36px;margin-top:36px;border-top:1px solid #DDE3EA;padding-top:22px}.after h2{font-size:22px}.after p,.after li{font-size:14px}.after ul{padding-left:19px}.after li{margin:8px 0}.review{background:#E8F0F8;border:1px solid #BFD4E8;border-radius:10px;padding:18px 22px;margin-top:28px}.review p{margin:0}footer{margin-top:25px;font-size:12px;color:#475569}code{font:12px Consolas,monospace;background:#F1F4F7;padding:2px 4px;border-radius:3px}::selection{background:#BFD4E8}@media(max-width:1050px){main{padding:22px}.grid{grid-template-columns:1fr}.card-head p{min-height:0}.preview img{max-height:720px;object-fit:contain}.principle{display:block}.principle p+p{margin-top:15px}.after{grid-template-columns:1fr;gap:20px}}@media(max-width:500px){main{padding:18px}.intro{font-size:16px}.card-head,.card-body{padding:18px}.review{padding:16px}h1{font-size:31px}}
</style></head><body><main><header><div class="top"><strong>Round 2 · Three GPT-6-Sol alternatives</strong><div><a href="../c-lanes/index.html">Revisit C</a> · <a href="../index.html">First round</a></div></div><h1>Make the design reasons visible.</h1><p class="intro">C made ownership and handoffs clearer. This round keeps that strength and tests how to explain why a boundary exists, what benefit it enables, and whether that benefit is implemented.</p></header>
<div class="principle"><p><strong>What we keep</strong>Visible owners, meaningful connectors, parallel work and explicit failure consequences.</p><p><strong>What we test</strong>Purpose beside the flow, aligned examples, or connected boundary closeups.</p><p><strong>What must transfer</strong>Reusable instructions describe relationships and evidence. They do not require this app, models, caching, or a fixed number of lanes.</p></div>
<div class="grid">@@CARDS@@</div>
<div class="after"><section><h2>Evaluate the explanation</h2><ul><li>Can you explain the reason for a separation without inferring it?</li><li>Can you distinguish current behavior from a proposed benefit?</li><li>Do placement and arrows help you understand the relationship?</li><li>Which view would still work for a different system or workflow?</li></ul><p>The prototypes use the same app as a test case. Their rationales include unrelated hypothetical workflows to check whether the instructions transfer.</p></section><section><h2>Portable instructions, separate from the example</h2><p>Each candidate includes its own generic proposal. A shared draft collects the principles this round is testing: choose the form from the reader’s question; explain consequential boundaries; keep important branches visible; and mark evidence and status where they affect the claim.</p><p><a href="GENERIC-INSTRUCTIONS.md">Read the shared generic draft</a> · <a href="BRIEF.md">Round brief</a></p><p><b>Current vs proposed:</b> the app’s two-message request is implemented. Deliberate provider caching and its measurement remain proposed; neither the diagrams nor this design round implement them.</p></section></div>
<div class="review"><p><b>Review choices: E, F or G.</b> You can retain one, combine useful parts, or identify what still requires too much inference. No final direction or installed-skill change is recorded.</p></div>
<footer>Review checked source claims, portable proposal wording, desktop/narrow rendering, offline assets, anchor targets and no-script reading in Edge. These checks do not establish user comprehension or live app execution. Previews are screenshots of the explanation prototypes. Results: <code>design/alternatives/round-2/proof/</code>.</footer>
</main></body></html>'''.replace("@@CARDS@@", "\n".join(cards))
page = page.replace("Three GPT-6-Sol alternatives", "Three presentation alternatives")
page = page.replace('<div class="after">', retained + '<div class="after">')
page = page.replace('</style>', '.retained{margin-top:36px;border-top:1px solid #DDE3EA;padding-top:24px}.overview{overflow:auto;background:white;border:1px solid #DDE3EA;border-radius:12px;padding:18px}.caption,figcaption{font-size:12px;color:#475569}.capture-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:30px;margin-top:24px}.capture-grid figure{margin:0}.app-shot{width:100%;max-width:680px;height:auto;border:1px solid #DDE3EA;border-radius:8px}.capture-grid h3{font-size:18px}.capture-grid figcaption{margin-top:9px}@media(max-width:750px){.capture-grid{grid-template-columns:1fr}} </style>')
(ROOT / "index.html").write_text(page, encoding="utf-8")
print(ROOT / "index.html")
